# Site settings
title:       C++ and GUI Development Guidelines
email:       max.jendruk@student.hpi.de
author:      hpicgs 
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl:     "/guidelines"

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    "/:year/:month/:day/:title/"
paginate:     5
paginate_path: "/articles/page:num/"
sass:
  compressed: true

default:
  scope:
    path: ""
    type: "post"
  values:
    layout: post
  scope:
    path: ""
    type: "pages"
  values:
    in_menu: no
    weight: 0


