# Site settings
timezone: Europe/Berlin

baseurl: '/guidelines' # the subpath of your site, e.g. /blog/
url: 'https://cginternals.github.io/guidelines' # the base hostname & protocol for your site

title: 'C++ Programming Guidelines'
author: 'CG Internals, Potsdam, Germany'

google_font_sans_serif: 'Source+Sans+Pro:600,300'
google_font_monospace: 'Source+Code+Pro:400'

# Handling Reading
safe: true
encoding: utf-8

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

permalink: "articles/:title/"
#paginate:     5
#aginate_path: "/articles/page/:num"

# Outputting
exclude: [
  '.htpasswd',
  'node_modules',
  'Gemfile',
  'vendor']

default:
  scope:
    path: ""
    type: "post"
  values:
    layout: post
  scope:
    path: ""
    type: "pages"
  values:
    in_menu: no
    weight: 0

# CSS Minification
sass:
  style: compressed
